import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';
import { Chat } from 'components/Chat';
import { trpc } from '../utils/trpc';
import { useState } from 'react';
import VideoBackground from 'components/VideoBackground';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <VideoBackground />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="goldeffect gold mx-auto flex flex-col items-center justify-center gap-10 px-6 py-8 font-LOTR md:h-screen">
        <h1 className=" goldeffect gold text-[100px]">
          Welcome to Greens & Foxes
        </h1>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const s = useSession();
  s.data?.user?.id;

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );
  console.log(sessionData);
  const [message, setMessage] = useState<string>(
    'This is the subscription field',
  );
  trpc.wsRouter.sub.useSubscription(undefined, {
    onData(data: any) {
      setMessage(data);
    },
  });
  const messenger = trpc.wsRouter.input.useMutation();
  const handleChange = (ev: React.FormEvent<EventTarget>) => {
    const target: HTMLInputElement = ev.target as HTMLInputElement;

    messenger.mutate({ typing: target.value });
  };
  return (
    <div className="text-[40px]">
      <p>{sessionData?.user?.email}</p>
      <p>{sessionData?.user?.id}</p>

      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="goldeffect mr-12 "
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? 'Log Out' : 'Log In'}
      </button>
      <Link className="goldeffect" href={'/register'}>
        Register
      </Link>
    </div>
  );
};
